#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HealthFlow Guinea - Rapport d'Audit, Recommandations et Evolutions
Professional PDF report generated via ReportLab
"""

import os
import sys
import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether,
    CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import SimpleDocTemplate

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: nature | Mode: minimal | Harmony: analogous
# Contrast: text:bg=14.54 | accent:bg=4.46
ACCENT       = colors.HexColor('#217591')
TEXT_PRIMARY  = colors.HexColor('#1b1c1e')
TEXT_MUTED    = colors.HexColor('#6d7278')
BG_SURFACE   = colors.HexColor('#dcdfe4')
BG_PAGE      = colors.HexColor('#ebedf0')

# ReportLab table colors
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# Severity colors
SEV_CRITICAL = colors.HexColor('#dc2626')
SEV_HIGH     = colors.HexColor('#ea580c')
SEV_MEDIUM   = colors.HexColor('#ca8a04')
SEV_LOW      = colors.HexColor('#16a34a')

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('NotoSerifSC', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSCReg', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSansReg', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSansBold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('NotoSerifSC', normal='NotoSerifSCReg', bold='NotoSerifSC')
registerFontFamily('DejaVuSansReg', normal='DejaVuSansReg', bold='DejaVuSansBold')

# Font fallback: Register Times New Roman alias for compatibility
# Some default styles reference 'Times New Roman'
pdfmetrics.registerFont(TTFont('TimesNewRoman', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('TimesNewRoman-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
registerFontFamily('Times-Roman', normal='TimesNewRoman', bold='TimesNewRoman-Bold')
# Also register as 'Times New Roman' for compatibility
registerFontFamily('TimesNewRoman', normal='TimesNewRoman', bold='TimesNewRoman-Bold')

# Override default styles that reference 'Times New Roman'
from reportlab.lib.fonts import addMapping
addMapping('TimesNewRoman', 0, 0, 'TimesNewRoman')
addMapping('TimesNewRoman', 1, 0, 'TimesNewRoman-Bold')
addMapping('TimesNewRoman', 0, 1, 'TimesNewRoman')
addMapping('TimesNewRoman', 1, 1, 'TimesNewRoman-Bold')

# ━━ Page Dimensions ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
CONTENT_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Styles ━━
# We need to register fonts with the EXACT name 'Times New Roman' because
# getSampleStyleSheet() and <b> tags resolve to that name internally
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('TimesNewRoman-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='TimesNewRoman-Bold')
addMapping('Times New Roman', 0, 0, 'Times New Roman')
addMapping('Times New Roman', 1, 0, 'TimesNewRoman-Bold')
addMapping('Times New Roman', 0, 1, 'Times New Roman')
addMapping('Times New Roman', 1, 1, 'TimesNewRoman-Bold')

styles = getSampleStyleSheet()

# French body style
body_style = ParagraphStyle(
    name='FRBody',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_JUSTIFY,
    spaceBefore=0,
    spaceAfter=6,
    wordWrap='CJK',
)

body_left = ParagraphStyle(
    name='FRBodyLeft',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_LEFT,
    spaceBefore=0,
    spaceAfter=6,
    wordWrap='CJK',
)

# Heading styles
h1_style = ParagraphStyle(
    name='FRH1',
    fontName='LiberationSerif',
    fontSize=20,
    leading=28,
    alignment=TA_LEFT,
    textColor=ACCENT,
    spaceBefore=18,
    spaceAfter=12,
)

h2_style = ParagraphStyle(
    name='FRH2',
    fontName='LiberationSerif',
    fontSize=15,
    leading=22,
    alignment=TA_LEFT,
    textColor=TEXT_PRIMARY,
    spaceBefore=14,
    spaceAfter=8,
)

h3_style = ParagraphStyle(
    name='FRH3',
    fontName='LiberationSerif',
    fontSize=12,
    leading=18,
    alignment=TA_LEFT,
    textColor=TEXT_PRIMARY,
    spaceBefore=10,
    spaceAfter=6,
)

# Table styles
table_header_style = ParagraphStyle(
    name='TableHeader',
    fontName='LiberationSerif',
    fontSize=10,
    leading=14,
    textColor=colors.white,
    alignment=TA_CENTER,
)

table_cell_style = ParagraphStyle(
    name='TableCell',
    fontName='LiberationSerif',
    fontSize=9.5,
    leading=14,
    textColor=TEXT_PRIMARY,
    alignment=TA_LEFT,
)

table_cell_center = ParagraphStyle(
    name='TableCellCenter',
    fontName='LiberationSerif',
    fontSize=9.5,
    leading=14,
    textColor=TEXT_PRIMARY,
    alignment=TA_CENTER,
)

# Caption style
caption_style = ParagraphStyle(
    name='Caption',
    fontName='LiberationSerif',
    fontSize=9,
    leading=13,
    textColor=TEXT_MUTED,
    alignment=TA_CENTER,
    spaceBefore=3,
    spaceAfter=6,
)

# Bullet style
bullet_style = ParagraphStyle(
    name='Bullet',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_LEFT,
    leftIndent=20,
    bulletIndent=6,
    spaceBefore=2,
    spaceAfter=2,
    wordWrap='CJK',
)

# Callout / highlight style
callout_style = ParagraphStyle(
    name='Callout',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_LEFT,
    leftIndent=16,
    borderPadding=8,
    spaceBefore=6,
    spaceAfter=6,
    backColor=colors.HexColor('#f0f7fa'),
    borderWidth=0,
    wordWrap='CJK',
)

# TOC styles
toc_h1_style = ParagraphStyle(
    name='TOCH1',
    fontName='LiberationSerif',
    fontSize=13,
    leftIndent=20,
    spaceBefore=6,
    spaceAfter=3,
    textColor=TEXT_PRIMARY,
)
toc_h2_style = ParagraphStyle(
    name='TOCH2',
    fontName='LiberationSerif',
    fontSize=11,
    leftIndent=40,
    spaceBefore=3,
    spaceAfter=2,
    textColor=TEXT_MUTED,
)

# ━━ TocDocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ━━ Helpers ━━
H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, h1_style, level=0),
    ]

def make_table(data, col_widths, caption_text=None):
    """Create a styled table with optional caption."""
    elements = []
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    elements.append(Spacer(1, 18))
    elements.append(t)
    if caption_text:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption_text, caption_style))
    elements.append(Spacer(1, 18))
    return elements

def sev_badge(level):
    """Return a colored severity badge paragraph."""
    color_map = {
        'CRITIQUE': SEV_CRITICAL,
        'ELEVEE': SEV_HIGH,
        'MOYENNE': SEV_MEDIUM,
        'FAIBLE': SEV_LOW,
    }
    c = color_map.get(level, TEXT_MUTED)
    return Paragraph('<b>%s</b>' % level, ParagraphStyle(
        name='SevBadge_%s' % level,
        fontName='Times New Roman',
        fontSize=9,
        leading=13,
        textColor=c,
        alignment=TA_CENTER,
    ))

# ━━ Build Document ━━
output_path = '/home/z/my-project/download/HealthFlow_Guinea_Audit_Rapport.pdf'
body_path = '/home/z/my-project/download/audit_body.pdf'

doc = TocDocTemplate(
    body_path,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
)

story = []

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TABLE OF CONTENTS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.append(Paragraph('<b>Table des Matieres</b>', ParagraphStyle(
    name='TOCTitle',
    fontName='Times New Roman',
    fontSize=22,
    leading=30,
    alignment=TA_LEFT,
    textColor=ACCENT,
    spaceBefore=20,
    spaceAfter=20,
)))
toc = TableOfContents()
toc.levelStyles = [toc_h1_style, toc_h2_style]
story.append(toc)
story.append(PageBreak())

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 1: RESUME EXECUTIF
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('1. Resume Executif'))

story.append(Paragraph(
    "HealthFlow Guinea est un systeme d'information hospitalier (SIH) ambitieux concu pour l'infrastructure "
    "sanitaire nationale de la Republique de Guinee. Developpe par DataSphere Innovation, sous la direction "
    "de Sekouna KABA, ce projet vise a fournir une plateforme complete couvrant la gestion des patients, "
    "les consultations cliniques, la telemedecine, les paiements Mobile Money, l'interopabilite HL7 FHIR R4, "
    "et les integrations nationales (DHIS2, SNIS, mTrac, SANTEP). Le systeme adopte une approche offline-first "
    "adaptee aux realites connectives de la Guinee, avec support PWA et IndexedDB pour le fonctionnement "
    "sans connexion internet.",
    body_style
))

story.append(Paragraph(
    "Cependant, cet audit revele des vulnerabilites de securite critiques qui compromettent gravement la "
    "confidentialite des donnees de sante, l'integrite du systeme d'authentification, et la conformite "
    "reglementaire. Les principales preoccupations incluent un chiffrement côté client qui n'est qu'un "
    "encodage base64, un hachage de mots de passe non cryptographique, des OTP renvoyes dans les reponses "
    "API, et une validation d'identite basee sur des en-tetes HTTP falsifiables. Ce rapport presente une "
    "analyse detaillee de 12 vulnerabilites critiques, des recommandations priorisees pour la mise en "
    "production, et une feuille de route pour les evolutions futures du systeme.",
    body_style
))

# Summary metrics table
summary_data = [
    [Paragraph('<b>Indicateur</b>', table_header_style),
     Paragraph('<b>Valeur</b>', table_header_style),
     Paragraph('<b>Appreciation</b>', table_header_style)],
    [Paragraph('Modules fonctionnels', table_cell_style),
     Paragraph('30+', table_cell_center),
     Paragraph('Tres bon', table_cell_center)],
    [Paragraph('Vulnerabilites critiques', table_cell_style),
     Paragraph('6', table_cell_center),
     sev_badge('CRITIQUE')],
    [Paragraph('Vulnerabilites elevees', table_cell_style),
     Paragraph('5', table_cell_center),
     sev_badge('ELEVEE')],
    [Paragraph('Vulnerabilites moyennes', table_cell_style),
     Paragraph('3', table_cell_center),
     sev_badge('MOYENNE')],
    [Paragraph('Routes API', table_cell_style),
     Paragraph('30+', table_cell_center),
     Paragraph('Bon volume', table_cell_center)],
    [Paragraph('Couverture de tests', table_cell_style),
     Paragraph('0%', table_cell_center),
     sev_badge('CRITIQUE')],
    [Paragraph('Langues supportees', table_cell_style),
     Paragraph('5', table_cell_center),
     Paragraph('Excellent', table_cell_center)],
    [Paragraph('Modeles Prisma', table_cell_style),
     Paragraph('40+', table_cell_center),
     Paragraph('Tres bon', table_cell_center)],
    [Paragraph('Niveau de maturite production', table_cell_style),
     Paragraph('Prototype avance', table_cell_center),
     sev_badge('MOYENNE')],
]
story.extend(make_table(summary_data, [CONTENT_WIDTH*0.45, CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.30],
                        "Tableau 1 : Synthese des indicateurs cles du projet HealthFlow Guinea"))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 2: ANALYSE DE L'ARCHITECTURE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('2. Analyse de l\'Architecture'))

story.append(add_heading('2.1 Stack Technique et Infrastructure', h2_style, level=1))
story.append(Paragraph(
    "Le projet repose sur Next.js 16.1.3 avec le App Router, React 19, TypeScript 5, Tailwind CSS 4, et "
    "shadcn/ui pour l'interface utilisateur. La persistance des donnees est assuree par Prisma ORM avec SQLite "
    "en developpement et PostgreSQL provisionne via Docker Compose en production. L'etat applicatif est gere "
    "par Zustand avec persistance localStorage, complete par IndexedDB pour le mode hors-ligne. La securite "
    "repose sur Next-Auth avec authentification Phone+OTP, un systeme RBAC a 8 roles, et un RLS (Row-Level "
    "Security) au niveau applicatif. L'infrastructure Docker inclut PostgreSQL 16, Redis 7, et Nginx comme "
    "reverse proxy avec rate limiting.",
    body_style
))

story.append(add_heading('2.2 Forces Architecturales', h2_style, level=1))

forces = [
    ("<b>Modelisation domaine healthcare complet</b> : Les types FHIR R4, la matrice RBAC, le MPI "
     "(Master Patient Index), et les integrations nationales (DHIS2, SNIS, mTrac) temoignent d'une "
     "connaissance approfondie du domaine sante guineen. La couverture fonctionnelle est impressionnante "
     "avec plus de 30 modules couvrant l'ensemble du cycle de soins."),
    ("<b>Conception offline-first</b> : L'architecture IndexedDB + Service Worker + file de synchronisation "
     "est correctement implementee avec trois strategies de cache (Cache-First pour les statiques, "
     "Network-First pour les API, Stale-While-Revalidate pour les pages). Cette approche est essentielle "
     "pour le contexte guineen ou la connectivite est intermittente."),
    ("<b>Structure modulaire claire</b> : La separation entre lib (logique metier), components (UI), "
     "hooks (reactivite), et API routes (endpoints) suit les bonnes pratiques Next.js. Chaque module "
     "metier (telemedecine, pharmacie, laboratoire, etc.) est correctement isole."),
    ("<b>Localisation Guinee-specifique</b> : Le support de 5 langues (Francais, Anglais, Malinke, "
     "Soussou, Poular), les codes de zones sanitaires, les etablissements de sante, et les systemes "
     "nationaux de sante publique montrent un engagement reel dans l'adaptation locale."),
    ("<b>Infrastructure Docker production-ready</b> : Le Dockerfile multi-stage, le docker-compose avec "
     "PostgreSQL et Redis, et le script de deploiement demontrent une vision de mise en production."),
]
for f in forces:
    story.append(Paragraph(f, bullet_style, bulletText=chr(8226)))

story.append(add_heading('2.3 Faiblesses Architecturales', h2_style, level=1))

faiblesses = [
    ("<b>Routage cote client uniquement</b> : L'application utilise un unique page.tsx avec basculement "
     "de vues via Zustand au lieu du routage fichier de Next.js. Cela rend le SEO impossible, les liens "
     "profonds non fonctionnels, et la navigation par URL inexistante. C'est un anti-pattern majeur pour "
     "une application de cette envergure."),
    ("<b>Donnees de demo dans les constructeurs</b> : Chaque service initialise avec des donnees en dur "
     "dans ses constructeurs (~700 lignes dans data-store.ts). Cela rend la transition vers la production "
     "extremement difficile et pollue le code metier avec des donnees de test."),
    ("<b>Tout en memoire</b> : Les journaux d'audit, les sessions OTP, les echanges HIE, et les "
     "enregistrements MPI sont tous stockes en memoire. Un redemarrage serveur entraine une perte "
     "complete de ces donnees, ce qui est inacceptable pour un systeme de sante."),
    ("<b>Incoherence Prisma SQLite vs PostgreSQL</b> : Le schema Prisma definit SQLite mais le "
     "docker-compose provisionne PostgreSQL. Cette incoherence empeche le deploiement Docker de "
     "fonctionner correctement avec la base de donnees."),
    ("<b>Double systeme i18n concurrent</b> : Un fournisseur React Context personnalise et next-intl "
     "coexistent sans integration. next-intl est configure en dur sur le francais cote serveur, ignorant "
     "la locale cote client."),
]
for f in faiblesses:
    story.append(Paragraph(f, bullet_style, bulletText=chr(8226)))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 3: AUDIT DE SECURITE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('3. Audit de Securite'))

story.append(Paragraph(
    "L'audit de securite revele des vulnerabilites graves qui rendent le systeme actuel impropre a un "
    "deploiement en production dans un contexte de sante. Les donnees de sante sont classees donnees "
    "sensibles par la reglementation (equivalent RGPD/HIPAA), et toute fuite ou alteration pourrait "
    "avoir des consequences legales et ethiques severes. Cette section detaille les 12 vulnerabilites "
    "identifiees, classees par niveau de severite.",
    body_style
))

story.append(add_heading('3.1 Vulnerabilites Critiques (Niveau 1)', h2_style, level=1))

# Critical vulnerabilities table
crit_data = [
    [Paragraph('<b>ID</b>', table_header_style),
     Paragraph('<b>Vulnerabilite</b>', table_header_style),
     Paragraph('<b>Fichier</b>', table_header_style),
     Paragraph('<b>Impact</b>', table_header_style)],
    [Paragraph('SEC-01', table_cell_center),
     Paragraph('OTP renvoye dans la reponse API - tout appelant obtient le code OTP', table_cell_style),
     Paragraph('api/auth/otp/route.ts', table_cell_style),
     Paragraph('Contournement total de l\'authentification', table_cell_style)],
    [Paragraph('SEC-02', table_cell_center),
     Paragraph('CORS autorise toutes les origines (Access-Control-Allow-Origin: *)', table_cell_style),
     Paragraph('lib/api-utils.ts', table_cell_style),
     Paragraph('Acces API depuis n\'importe quel domaine', table_cell_style)],
    [Paragraph('SEC-03', table_cell_center),
     Paragraph('Chiffrement client = encodage base64 (btoa), reversible trivialement', table_cell_style),
     Paragraph('lib/security.ts', table_cell_style),
     Paragraph('Fausses donnees chiffrees lisibles par tous', table_cell_style)],
    [Paragraph('SEC-04', table_cell_center),
     Paragraph('Hachage mots de passe = DJB2 (non cryptographique, sans sel)', table_cell_style),
     Paragraph('lib/security.ts', table_cell_style),
     Paragraph('Mots de passe recuperables en clair', table_cell_style)],
    [Paragraph('SEC-05', table_cell_center),
     Paragraph('Role utilisateur depuis en-tetes HTTP falsifiables (x-user-role)', table_cell_style),
     Paragraph('lib/api-middleware.ts', table_cell_style),
     Paragraph('Escalade de privilegescarbitraire', table_cell_style)],
    [Paragraph('SEC-06', table_cell_center),
     Paragraph('Protection CSRF desactivee dans secureApiHandler', table_cell_style),
     Paragraph('lib/api-middleware.ts', table_cell_style),
     Paragraph('Attaques CSRF sur toutes les routes', table_cell_style)],
]
story.extend(make_table(crit_data,
    [CONTENT_WIDTH*0.08, CONTENT_WIDTH*0.35, CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.32],
    "Tableau 2 : Vulnerabilites critiques identifiees"))

# Detailed explanation of each critical vuln
story.append(add_heading('3.1.1 SEC-01 : OTP dans la reponse API', h3_style, level=1))
story.append(Paragraph(
    "Le systeme d'authentification Phone+OTP presente une faille fondamentale : le code OTP genere est "
    "retourne directement dans le corps de la reponse HTTP de l'endpoint /api/auth/otp. Cela signifie que "
    "tout acteur capable d'appeler cette API (application malveillante, script, navigateur compromis) "
    "obtient immediatement le code OTP sans necessiter d'acces au telephone du destinataire. Cette "
    "vulnerabilite annule completement le benefice de l'authentification a deux facteurs. Dans un systeme "
    "de sante, un attaquant pourrait usurper l'identite de n'importe quel professionnel de sante et acceder "
    "aux dossiers medicaux des patients, prescrire des medicaments, ou modifier des donnees cliniques.",
    body_style
))
story.append(Paragraph(
    "De plus, le stockage OTP en memoire (Map JavaScript) signifie que tous les OTP sont perdus lors "
    "d'un redemarrage serveur et ne sont pas partages entre les instances en cas de montee en charge. "
    "La correction immediate consiste a ne jamais retourner l'OTP dans la reponse API, a l'envoyer "
    "exclusivement par SMS via un fournisseur tiers (Orange Money API, Twilio), et a utiliser Redis "
    "pour le stockage OTP avec expiration automatique.",
    body_style
))

story.append(add_heading('3.1.2 SEC-03 : Faux chiffrement base64', h3_style, level=1))
story.append(Paragraph(
    "La fonction encryptField() dans lib/security.ts utilise btoa(encodeURIComponent(data)) comme "
    "mecanisme de chiffrement cote client. L'encodage base64 n'est PAS du chiffrement : il s'agit d'un "
    "encodage reversible trivialement decode avec atob(). N'importe quel developpeur ou outil automatique "
    "peut decoder ces donnees en une seule ligne de code. Cette vulnerabilite est particulierement grave "
    "car elle cree une illusion de securite sans fournir aucune protection reelle. Les donnees de sante "
    "ainsi 'chiffrees' sont en realite accessibles en clair a quiconque inspecte le trafic reseau ou le "
    "stockage local.",
    body_style
))
story.append(Paragraph(
    "Ironiquement, le serveur dispose d'une implementation correcte avec encryptFieldServer() utilisant "
    "AES-256-CBC via le module crypto de Node.js. La correction consiste a deplacer toutes les operations "
    "de chiffrement vers le serveur et a utiliser Web Crypto API (crypto.subtle) pour le chiffrement cote "
    "client lorsque cela est absolument necessaire, avec des cles gerees separement.",
    body_style
))

story.append(add_heading('3.2 Vulnerabilites Elevees (Niveau 2)', h2_style, level=1))

high_data = [
    [Paragraph('<b>ID</b>', table_header_style),
     Paragraph('<b>Vulnerabilite</b>', table_header_style),
     Paragraph('<b>Fichier</b>', table_header_style),
     Paragraph('<b>Impact</b>', table_header_style)],
    [Paragraph('SEC-07', table_cell_center),
     Paragraph('Secrets d\'auth codés en dur dans docker-compose (healthflow_secret_2024)', table_cell_style),
     Paragraph('docker-compose.yml', table_cell_style),
     Paragraph('Forgage de JWT possible', table_cell_style)],
    [Paragraph('SEC-08', table_cell_center),
     Paragraph('CSP autorise unsafe-inline et unsafe-eval', table_cell_style),
     Paragraph('middleware.ts', table_cell_style),
     Paragraph('Protection XSS significativement affaiblie', table_cell_style)],
    [Paragraph('SEC-09', table_cell_center),
     Paragraph('Token d\'auth dans localStorage (accessible via XSS)', table_cell_style),
     Paragraph('lib/auth-store.ts', table_cell_style),
     Paragraph('Vol de session par XSS', table_cell_style)],
    [Paragraph('SEC-10', table_cell_center),
     Paragraph('Aucune verification JWT dans les routes API', table_cell_style),
     Paragraph('Toutes les routes api/', table_cell_style),
     Paragraph('Acces non authentifie aux donnees', table_cell_style)],
    [Paragraph('SEC-11', table_cell_center),
     Paragraph('Cle secrete NextAuth avec fallback hardcoded', table_cell_style),
     Paragraph('lib/auth.ts', table_cell_style),
     Paragraph('JWT forgable si variable absente', table_cell_style)],
]
story.extend(make_table(high_data,
    [CONTENT_WIDTH*0.08, CONTENT_WIDTH*0.35, CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.32],
    "Tableau 3 : Vulnerabilites de niveau eleve"))

story.append(add_heading('3.3 Vulnerabilites Moyennes (Niveau 3)', h2_style, level=1))

med_data = [
    [Paragraph('<b>ID</b>', table_header_style),
     Paragraph('<b>Vulnerabilite</b>', table_header_style),
     Paragraph('<b>Fichier</b>', table_header_style),
     Paragraph('<b>Impact</b>', table_header_style)],
    [Paragraph('SEC-12', table_cell_center),
     Paragraph('ignoreBuildErrors: true masque les erreurs TypeScript', table_cell_style),
     Paragraph('next.config.ts', table_cell_style),
     Paragraph('Bugs silencieux en production', table_cell_style)],
    [Paragraph('SEC-13', table_cell_center),
     Paragraph('Toutes les regles ESLint desactivees', table_cell_style),
     Paragraph('eslint.config.mjs', table_cell_style),
     Paragraph('Aucune verification qualite automatisee', table_cell_style)],
    [Paragraph('SEC-14', table_cell_center),
     Paragraph('RLS applicative uniquement (non appliquee en BDD)', table_cell_style),
     Paragraph('lib/rls.ts', table_cell_style),
     Paragraph('Contournement possible via route non protegee', table_cell_style)],
]
story.extend(make_table(med_data,
    [CONTENT_WIDTH*0.08, CONTENT_WIDTH*0.35, CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.32],
    "Tableau 4 : Vulnerabilites de niveau moyen"))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 4: AUDIT DES PERFORMANCE ET QUALITE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('4. Performance et Qualite du Code'))

story.append(add_heading('4.1 Problemes de Performance', h2_style, level=1))

story.append(Paragraph(
    "L'audit de performance identifie plusieurs problemes qui afecteront significativement les temps de "
    "chargement et l'experience utilisateur en production, particulierement sur les connexions bas debit "
    "typiques en Guinee (2G/3G). Ces problemes doivent etre corriges avant toute mise en production car "
    "ils impactent directement la capacite du systeme a fonctionner dans son environnement cible.",
    body_style
))

perf_data = [
    [Paragraph('<b>Probleme</b>', table_header_style),
     Paragraph('<b>Detail</b>', table_header_style),
     Paragraph('<b>Impact</b>', table_header_style)],
    [Paragraph('Chargement eager des composants', table_cell_style),
     Paragraph('30+ composants de page importes dans page.tsx sans React.lazy() ni dynamic()', table_cell_style),
     Paragraph('Bundle JS initial excessif, premier chargement lent', table_cell_style)],
    [Paragraph('Donnees demo au chargement', table_cell_style),
     Paragraph('~700 lignes de donnees patients creees a chaque import du module data-store', table_cell_style),
     Paragraph('Memoire consommee inutilement, latence au demarrage', table_cell_style)],
    [Paragraph('Absence de pagination', table_cell_style),
     Paragraph('Tous les patients, rendez-vous, etc. charges en memoire simultanement', table_cell_style),
     Paragraph('Degradation progressive avec le volume de donnees', table_cell_style)],
    [Paragraph('Prisma query logging permanent', table_cell_style),
     Paragraph('log: ["query"] active dans toutes les configurations', table_cell_style),
     Paragraph('Overhead I/O inutile en production', table_cell_style)],
]
story.extend(make_table(perf_data,
    [CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.45, CONTENT_WIDTH*0.30],
    "Tableau 5 : Problemes de performance identifies"))

story.append(add_heading('4.2 Qualite du Code et Dette Technique', h2_style, level=1))

story.append(Paragraph(
    "La qualite du code presente un paradoxe interessant : d'un cote, la modelisation metier et la "
    "couverture fonctionnelle sont excellentes, temoignant d'une bonne comprehension du domaine sante ; "
    "de l'autre, les pratiques de developpement (validation, tests, typage) sont insuffisantes pour un "
    "projet de cette envergure. Le fichier de configuration ESLint desactive virtuellement toutes les "
    "regles significatives (no-explicit-any: off, no-unused-vars: off, exhaustive-deps: off), ce qui "
    "supprime la premiere ligne de defense contre les erreurs courantes. De meme, TypeScript est configure "
    "avec noImplicitAny: false et ignoreBuildErrors: true, creant une illusion de typage sans ses "
    "benefices reels.",
    body_style
))

story.append(Paragraph(
    "L'absence totale de tests (0% de couverture) est le probleme le plus preoccupant. Pour un systeme "
    "de sante ou les erreurs peuvent avoir des consequences vitales, cette absence est inacceptable. "
    "La dependance Zod est presente dans package.json mais n'est utilisee dans aucune route API, "
    "laissant les endpoints sans validation d'entree. Enfin, le nom du package reste "
    "nextjs_tailwind_shadcn_ts (nom du template par defaut), ce qui suggere que le projet n'a pas "
    "ete initialise avec une identite propre.",
    body_style
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 5: AUDIT FHIR ET INTEROPERABILITE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('5. FHIR R4 et Interoperabilite'))

story.append(add_heading('5.1 Implementation FHIR R4', h2_style, level=1))

story.append(Paragraph(
    "L'implementation FHIR R4 est l'un des points forts du projet, avec des definitions de types "
    "completes couvrant Patient, Observation, DiagnosticReport, Encounter, MedicationRequest, "
    "Practitioner, Organization, Bundle et OperationOutcome. Le mapping bidirectionnel (patientToFHIR / "
    "fhirToPatient) est correctement implemente, et les systemes de codes Guinee-specifiques (ID national, "
    "zones de sante, etablissements, formulaire national de medicaments, carte SANTEP) sont un atout "
    "majeur pour l'adoption du systeme dans le contexte national.",
    body_style
))

story.append(Paragraph(
    "Cependant, l'implementation actuelle reste conceptuelle : le endpoint /api/fhir/[...path] existe "
    "mais toutes les donnees sont en memoire ou de demonstration. Il n'y a pas de serveur FHIR reel "
    "avec persistance en base de donnees, pas d'implementation des parametres de recherche FHIR, "
    "pas d'operation $validate contre les profils HL7 officiels, et les signatures des Bundles ne "
    "contiennent aucune donnee cryptographique. Pour atteindre la conformite FHIR, le systeme doit "
    "implementer un serveur FHIR complet avec validation, recherche, et persistance.",
    body_style
))

story.append(add_heading('5.2 Integrations Nationales', h2_style, level=1))

integr_data = [
    [Paragraph('<b>Systeme</b>', table_header_style),
     Paragraph('<b>Statut</b>', table_header_style),
     Paragraph('<b>Ecarts</b>', table_header_style)],
    [Paragraph('DHIS2', table_cell_style),
     Paragraph('Structures de donnees definies', table_cell_style),
     Paragraph('Pas de client API reel, pas de push de donnees', table_cell_style)],
    [Paragraph('SNIS', table_cell_style),
     Paragraph('Indicateurs definis avec cibles et tendances', table_cell_style),
     Paragraph('Donnees demo uniquement, pas d\'integration API', table_cell_style)],
    [Paragraph('mTrac', table_cell_style),
     Paragraph('Alertes et rapports hebdomadaires definis', table_cell_style),
     Paragraph('Pas de client API mTrac', table_cell_style)],
    [Paragraph('SANTEP', table_cell_style),
     Paragraph('Structure carte electronique avec QR/NFC', table_cell_style),
     Paragraph('Pas de systeme d\'emission/verification', table_cell_style)],
    [Paragraph('HIE', table_cell_style),
     Paragraph('Echange inter-etablissements le plus complet', table_cell_style),
     Paragraph('En memoire uniquement, pas d\'appels reseau', table_cell_style)],
]
story.extend(make_table(integr_data,
    [CONTENT_WIDTH*0.18, CONTENT_WIDTH*0.38, CONTENT_WIDTH*0.44],
    "Tableau 6 : Statut des integrations nationales"))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 6: RECOMMANDATIONS PRIORISEES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('6. Recommandations Priorisees'))

story.append(add_heading('6.1 Actions Immediates - Securite (0-2 semaines)', h2_style, level=1))

story.append(Paragraph(
    "Ces actions sont indispensables avant toute mise en production ou demonstration publique du systeme. "
    "Elles concernent exclusivement la correction des vulnerabilites de securite critiques et elevees "
    "identifiees dans la section 3. Leur non-resolution expose le systeme a des risques juridiques et "
    "ethiques majeurs dans le contexte des donnees de sante.",
    body_style
))

imm_data = [
    [Paragraph('<b>Priorite</b>', table_header_style),
     Paragraph('<b>Action</b>', table_header_style),
     Paragraph('<b>Detail technique</b>', table_header_style),
     Paragraph('<b>Ref</b>', table_header_style)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Supprimer l\'OTP de la reponse API', table_cell_style),
     Paragraph('Envoyer uniquement par SMS via fournisseur tiers, stocker dans Redis avec TTL', table_cell_style),
     Paragraph('SEC-01', table_cell_center)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Restreindre CORS aux domaines autorises', table_cell_style),
     Paragraph('Remplacer * par la liste des domaines de confiance (frontend, admin)', table_cell_style),
     Paragraph('SEC-02', table_cell_center)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Remplacer le faux chiffrement par crypto.subtle', table_cell_style),
     Paragraph('Deplacer le chiffrement serveur (AES-256-CBC existant), Web Crypto API cote client', table_cell_style),
     Paragraph('SEC-03', table_cell_center)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Remplacer simpleHash par bcrypt/argon2', table_cell_style),
     Paragraph('Utiliser bcryptjs (compatible Edge) ou argon2 pour le hachage des mots de passe', table_cell_style),
     Paragraph('SEC-04', table_cell_center)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Verifier JWT dans le middleware API', table_cell_style),
     Paragraph('Utiliser getServerSession de NextAuth, ne jamais faire confiance aux en-tetes clients', table_cell_style),
     Paragraph('SEC-05', table_cell_center)],
    [Paragraph('P0', table_cell_center),
     Paragraph('Reactiver la protection CSRF', table_cell_style),
     Paragraph('Decommenter et activer la validation CSRF dans secureApiHandler', table_cell_style),
     Paragraph('SEC-06', table_cell_center)],
    [Paragraph('P1', table_cell_center),
     Paragraph('Rendre NEXTAUTH_SECRET obligatoire', table_cell_style),
     Paragraph('Supprimer le fallback hardcoded, faire echouer le demarrage si absent', table_cell_style),
     Paragraph('SEC-11', table_cell_center)],
    [Paragraph('P1', table_cell_center),
     Paragraph('Renforcer la CSP', table_cell_style),
     Paragraph('Supprimer unsafe-inline et unsafe-eval, utiliser des nonces ou hashes pour les scripts', table_cell_style),
     Paragraph('SEC-08', table_cell_center)],
]
story.extend(make_table(imm_data,
    [CONTENT_WIDTH*0.08, CONTENT_WIDTH*0.27, CONTENT_WIDTH*0.50, CONTENT_WIDTH*0.15],
    "Tableau 7 : Actions immediates de securite"))

story.append(add_heading('6.2 Actions a Court Terme - Architecture (2-8 semaines)', h2_style, level=1))

story.append(Paragraph(
    "Ces actions visent a transformer le prototype en une application production-ready. Elles concernent "
    "les corrections architecturales fondamentales qui permettront au systeme de passer a l'echelle et de "
    "fonctionner de maniere fiable dans un environnement de production.",
    body_style
))

court_data = [
    [Paragraph('<b>Action</b>', table_header_style),
     Paragraph('<b>Objectif</b>', table_header_style),
     Paragraph('<b>Approche recommandee</b>', table_header_style)],
    [Paragraph('Migrer vers le routage fichier Next.js', table_cell_style),
     Paragraph('SEO, liens profonds, navigation par URL', table_cell_style),
     Paragraph('Convertir les vues Zustand en routes /app avec layout.tsx par section', table_cell_style)],
    [Paragraph('Ajouter la validation Zod aux routes API', table_cell_style),
     Paragraph('Protection contre les injections et donnees invalides', table_cell_style),
     Paragraph('Creer des schemas Zod pour chaque endpoint, valider dans le middleware', table_cell_style)],
    [Paragraph('Extraire les donnees demo des constructeurs', table_cell_style),
     Paragraph('Separation code metier / donnees de test', table_cell_style),
     Paragraph('Scripts de seed Prisma, feature flag DEMO_MODE, variables d\'environnement', table_cell_style)],
    [Paragraph('Code splitting avec React.lazy()', table_cell_style),
     Paragraph('Reduction du bundle initial, chargement a la demande', table_cell_style),
     Paragraph('Dynamic imports pour chaque module page, Suspense boundaries', table_cell_style)],
    [Paragraph('Aligner Prisma sur PostgreSQL', table_cell_style),
     Paragraph('Coherence avec l\'infrastructure Docker', table_cell_style),
     Paragraph('Changer provider en postgresql, adapter le schema, tester les migrations', table_cell_style)],
    [Paragraph('Implementer un serveur FHIR avec persistance', table_cell_style),
     Paragraph('Conformite HL7 FHIR R4', table_cell_style),
     Paragraph('Stocker les ressources FHIR en BDD, implementer les parametres de recherche', table_cell_style)],
]
story.extend(make_table(court_data,
    [CONTENT_WIDTH*0.25, CONTENT_WIDTH*0.30, CONTENT_WIDTH*0.45],
    "Tableau 8 : Actions a court terme pour l\'architecture"))

story.append(add_heading('6.3 Actions a Moyen Terme - Production (2-6 mois)', h2_style, level=1))

moyen_items = [
    ("<b>Verification de session cote serveur</b> : Implementer getServerSession dans chaque route API "
     "pour verifier l'authenticite des requetes. Utiliser les tokens JWT avec rotation et expiration "
     "courte (15 minutes pour l'acces, 7 jours pour le refresh)."),
    ("<b>Row-Level Security au niveau base de donnees</b> : PostgreSQL offre des politiques RLS natives "
     "qui garantissent que chaque utilisateur ne peut acceder qu'aux donnees de son etablissement et de "
     "son role. Cela fournit une defense en profondeur au-dela du filtrage applicatif."),
    ("<b>Redis pour le stockage OTP et le rate limiting</b> : Deja provisionne dans docker-compose, Redis "
     "doit etre utilise pour les OTP (avec TTL automatique), les sessions, et le rate limiting distribue "
     "entre les instances."),
    ("<b>Clients API reels pour DHIS2/SNIS/mTrac</b> : Implementer des clients HTTP avec retry, circuit "
     "breaker, et gestion des erreurs pour chaque integration nationale. Utiliser les SDK officiels "
     "lorsqu'ils existent."),
    ("<b>Suite de tests complete</b> : Objectif de couverture minimum 80% avec tests unitaires (Vitest), "
     "tests d'integration (Testing Library), et tests E2E (Playwright). Prioriser les tests sur les "
     "flux critiques : authentification, prescription, paiement Mobile Money."),
    ("<b>Chiffrement de bout en bout pour le HIE</b> : Les echanges de donnees de sante entre "
     "etablissements doivent etre chiffres en transit (TLS 1.3) et au repos (AES-256), avec gestion "
     "des cles par etablissement et audit trail des acces."),
]
for item in moyen_items:
    story.append(Paragraph(item, bullet_style, bulletText=chr(8226)))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 7: EVOLUTIONS ET FEUILLE DE ROUTE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('7. Evolutions et Feuille de Route'))

story.append(add_heading('7.1 Phase 8 : Securisation et Conformite', h2_style, level=1))

story.append(Paragraph(
    "La Phase 8 constitue la priorite absolue et doit preceder toute autre evolution. Elle se concentre "
    "sur la correction de toutes les vulnerabilites identifiees dans cet audit et la mise en conformite "
    "du systeme avec les exigences reglementaires applicables aux donnees de sante. Cette phase inclut "
    "la refonte du systeme d'authentification, l'implementation du chiffrement reel, la verification "
    "JWT dans toutes les routes API, la RLS au niveau base de donnees, et l'audit trail persistant. "
    "La duree estimee est de 4 a 6 semaines avec un objectif de conformite aux normes equivalentes "
    "a HIPAA et RGPD pour les donnees de sante.",
    body_style
))

story.append(add_heading('7.2 Phase 9 : Architecture Production-Ready', h2_style, level=1))

story.append(Paragraph(
    "La Phase 9 transforme le prototype en une application production-ready. Les chantiers principaux "
    "incluent la migration vers le routage fichier Next.js (remplacement du routage Zustand par les "
    "routes /app), la mise en place de la validation Zod sur toutes les routes API, l'extraction des "
    "donnees de demo vers des scripts de seed, et l'implementation du code splitting avec React.lazy() "
    "pour reduire le bundle initial. Cette phase inclut egalement la migration vers PostgreSQL avec "
    "les politiques RLS natives, l'implementation d'un vrai serveur FHIR avec persistance, et la "
    "configuration d'un pipeline CI/CD avec tests automatiques. La duree estimee est de 6 a 10 semaines.",
    body_style
))

story.append(add_heading('7.3 Phase 10 : Integrations Nationales Reelles', h2_style, level=1))

story.append(Paragraph(
    "La Phase 10 materialise les integrations nationales actuellement definies conceptuellement. Le "
    "premier chantier est le connecteur DHIS2 avec synchronisation automatique des indicateurs sanitaires, "
    "suivi du connecteur SNIS pour la generation et le push des rapports mensuels, du connecteur mTrac "
    "pour la surveillance epidemiologique en temps reel, et du systeme SANTEP pour l'emission et la "
    "verification des cartes de sante electroniques. Le Health Information Exchange (HIE) doit etre "
    "implemente avec un chiffrement de bout en bout et une gestion des consentements patients conforme "
    "aux reglementations guineennes. La duree estimee est de 8 a 12 semaines, avec des livraisons "
    "incrementales par connecteur.",
    body_style
))

story.append(add_heading('7.4 Phase 11 : Intelligence Artificielle et Telemedecine Avancee', h2_style, level=1))

story.append(Paragraph(
    "La Phase 11 enrichit les capacites d'IA du systeme. L'assistant diagnostique actuel doit etre "
    "connecte a de vrais modeles d'IA (via API securisee) avec validation clinique, les interactions "
    "medicamenteuses doivent s'appuyer sur la base de donnees nationale des medicaments, et la "
    "surveillance epidemiologique doit utiliser des modeles predictifs pour les alertes precoces. "
    "La telemedecine doit evoluer vers la videoconsultation avec WebRTC, le partage d'ecran pour "
    "l'imagerie medicale, et l'integration avec les appareils de diagnostic portables (echographes, "
    "tensiometres connectes). Cette phase inclut egalement l'implementation de l'IA pour le tri "
    "automatique des urgences et la detection des epidemies. La duree estimee est de 10 a 16 semaines.",
    body_style
))

story.append(add_heading('7.5 Phase 12 : Deploiement National et Passage a l\'Echelle', h2_style, level=1))

story.append(Paragraph(
    "La Phase 12 constitue le deploiement a l'echelle nationale. Les chantiers incluent l'architecture "
    "multi-tenant pour supporter les 8 zones sanitaires et les etablissements de sante de toutes les "
    "regions, l'optimisation pour les connexions bas debit (2G/3G) avec compression et progressive "
    "loading, le deploiement sur infrastructure cloud guineenne ou regionale avec haute disponibilite, "
    "et la formation des agents de sante communautaire (ASC) avec des interfaces simplifiees en langues "
    "locales. Le systeme doit pouvoir supporter simultanement des milliers d'utilisateurs sur l'ensemble "
    "du territoire national avec une disponibilite de 99.5%. Cette phase inclut egalement la mise en "
    "place d'un systeme de support technique national et la certification officielle du systeme par les "
    "autorites de sante guineennes. La duree estimee est de 12 a 20 semaines.",
    body_style
))

# Roadmap summary table
roadmap_data = [
    [Paragraph('<b>Phase</b>', table_header_style),
     Paragraph('<b>Thematique</b>', table_header_style),
     Paragraph('<b>Duree estimee</b>', table_header_style),
     Paragraph('<b>Prerequis</b>', table_header_style)],
    [Paragraph('Phase 8', table_cell_center),
     Paragraph('Securisation et Conformite', table_cell_style),
     Paragraph('4-6 semaines', table_cell_center),
     Paragraph('Aucun', table_cell_style)],
    [Paragraph('Phase 9', table_cell_center),
     Paragraph('Architecture Production-Ready', table_cell_style),
     Paragraph('6-10 semaines', table_cell_center),
     Paragraph('Phase 8 terminee', table_cell_style)],
    [Paragraph('Phase 10', table_cell_center),
     Paragraph('Integrations Nationales Reelles', table_cell_style),
     Paragraph('8-12 semaines', table_cell_center),
     Paragraph('Phase 9 terminee', table_cell_style)],
    [Paragraph('Phase 11', table_cell_center),
     Paragraph('IA et Telemedecine Avancee', table_cell_style),
     Paragraph('10-16 semaines', table_cell_center),
     Paragraph('Phase 9 terminee (parallele possible avec Phase 10)', table_cell_style)],
    [Paragraph('Phase 12', table_cell_center),
     Paragraph('Deploiement National', table_cell_style),
     Paragraph('12-20 semaines', table_cell_center),
     Paragraph('Phases 10-11 validees', table_cell_style)],
]
story.extend(make_table(roadmap_data,
    [CONTENT_WIDTH*0.12, CONTENT_WIDTH*0.30, CONTENT_WIDTH*0.18, CONTENT_WIDTH*0.40],
    "Tableau 9 : Feuille de route des evolutions"))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 8: RECOMMANDATIONS DOCKER ET DEVOPS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('8. Recommandations DevOps et Infrastructure'))

story.append(add_heading('8.1 Ameliorations Docker', h2_style, level=1))

story.append(Paragraph(
    "L'infrastructure Docker existante est un bon point de depart mais necessite des ajustements "
    "critiques avant le deploiement en production. Les identifiants par defaut cods en dur dans le "
    "docker-compose.yml (healthflow_secret_2024, hf-guinea-secret-change-in-production-2024) doivent "
    "etre remplaces par des variables d'environnement injectees au deploiement, sans valeur par defaut. "
    "Les ports PostgreSQL (5432) et Redis (6379) exposes sur l'hote constituent un risque de securite "
    "en production et doivent etre restreints au reseau Docker interne. Le pgAdmin en developpement "
    "ne doit jamais avoir PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False.",
    body_style
))

docker_rec = [
    ("<b>Secret management</b> : Utiliser Docker Secrets ou un coffre-fort de secrets (HashiCorp Vault) "
     "pour gerer les mots de passe et cles API. Ne jamais stocker de secrets dans le code source ou "
     "les fichiers docker-compose."),
    ("<b>Health checks</b> : Ajouter des health checks pour PostgreSQL, Redis, et Nginx dans le "
     "docker-compose. Le health check existant sur /api/health est un bon debut."),
    ("<b>Resource limits</b> : Definir des limites de memoire et CPU pour chaque conteneur (deploy.resources "
     "dans docker-compose) pour eviter qu'un service ne consomme toutes les ressources."),
    ("<b>Logging centralise</b> : Configurer un pilote de logging (json-file avec rotation, ou Loki) "
     "pour eviter que les logs ne remplissent le disque."),
    ("<b>Backup automatise</b> : Implementer des sauvegardes automatiques de PostgreSQL avec "
     "pg_dump programmees et stockees sur un stockage externe chiffre."),
]
for item in docker_rec:
    story.append(Paragraph(item, bullet_style, bulletText=chr(8226)))

story.append(add_heading('8.2 Pipeline CI/CD', h2_style, level=1))

story.append(Paragraph(
    "Un pipeline CI/CD est indispensable pour garantir la qualite continue du code et la fiabilite "
    "des deploiements. Le pipeline recommande comprend les etapes suivantes : analyse statique "
    "(ESLint avec regles strictes, TypeScript strict mode), tests unitaires et d'integration avec "
    "couverture minimale de 80%, scan de securite des dependances (npm audit, Snyk), build et test "
    "de l'image Docker, deploiement automatise en staging avec tests de smoke, et deploiement en "
    "production apres validation manuelle. Les outils recommandes sont GitHub Actions ou GitLab CI "
    "pour l'orchestration, SonarQube pour l'analyse de qualite, et Trivy pour le scan des images "
    "Docker.",
    body_style
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 9: CONCLUSION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('9. Conclusion et Perspectives'))

story.append(Paragraph(
    "HealthFlow Guinea est un projet ambitieux et prometteur qui demontre une comprehension profonde "
    "des enjeux sanitaires guineens et une couverture fonctionnelle impressionnante. La modelisation "
    "FHIR R4, les integrations nationales (DHIS2, SNIS, mTrac, SANTEP), le support multilingue avec "
    "les langues locales, et l'approche offline-first sont des atouts majeurs qui positionnent ce "
    "systeme comme une solution potentiellement transformatrice pour le systeme de sante guineen.",
    body_style
))

story.append(Paragraph(
    "Cependant, l'audit revele que le systeme est actuellement au stade de prototype avance et ne peut "
    "en aucun cas etre deploie en production sans la correction prealable des vulnerabilites de securite "
    "critiques. Les 6 vulnerabilites critiques identifiees (OTP dans la reponse API, CORS ouvert, faux "
    "chiffrement, hachage non cryptographique, en-tetes falsifiables, CSRF desactive) constituent des "
    "risques majeurs pour la confidentialite des donnees de sante et la securite du systeme. Leur "
    "correction doit etre la priorite absolue, avant toute autre evolution fonctionnelle.",
    body_style
))

story.append(Paragraph(
    "La feuille de route proposee en 5 phases (Securisation, Architecture, Integrations, IA, Deploiement "
    "national) offre un chemin structure vers un systeme production-ready et deployable a l'echelle "
    "nationale. Avec un investissement estime de 40 a 64 semaines de developpement, HealthFlow Guinea "
    "a le potentiel de devenir le systeme d'information hospitalier de reference pour la Guinee et un "
    "modele pour les pays d'Afrique de l'Ouest confrontes aux memes defis sanitaires et technologiques.",
    body_style
))

# Build the body PDF
doc.multiBuild(story)
print(f"Body PDF generated: {body_path}")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# COVER PAGE GENERATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
cover_html_path = '/home/z/my-project/download/audit_cover.html'
cover_pdf_path = '/home/z/my-project/download/audit_cover.pdf'

# Template 01: HUD Data Terminal - Ultra-Thick Vertical Anchor Line
cover_html = """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800;900&family=Noto+Sans:wght@400;700&display=swap');

@page {
  size: 794px 1123px;
  margin: 0;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

html, body {
  width: 794px;
  height: 1123px;
  overflow: hidden;
  background: #ffffff;
  font-family: 'Inter', 'Noto Sans', sans-serif;
}

.cover-container {
  position: absolute;
  inset: 0;
  width: 794px;
  height: 1123px;
}

/* Layer 1: Background Grid */
.bg-layer {
  position: absolute;
  inset: 0;
  z-index: 1;
  overflow: hidden;
}

.grid-pattern {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(33,117,145,0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(33,117,145,0.03) 1px, transparent 1px);
  background-size: 50px 50px;
}

/* Layer 2: Structure */
.struct-layer {
  position: absolute;
  inset: 0;
  z-index: 2;
  overflow: visible;
}

.anchor-line {
  position: absolute;
  left: 95px;
  top: 112px;
  width: 6px;
  height: 898px;
  background: #217591;
}

.meta-separator {
  position: absolute;
  left: 125px;
  top: 740px;
  width: 318px;
  height: 1px;
  background: rgba(33,117,145,0.4);
}

/* Layer 3: Content */
.content-layer {
  position: absolute;
  inset: 0;
  z-index: 3;
  overflow: visible;
}

.kicker {
  position: absolute;
  left: 125px;
  top: 168px;
  font-size: 16px;
  font-weight: 400;
  letter-spacing: 3px;
  opacity: 0.6;
  color: #1b1c1e;
  text-transform: uppercase;
}

.hero-title {
  position: absolute;
  left: 125px;
  top: 250px;
  font-size: 52px;
  font-weight: 900;
  line-height: 1.15;
  color: #217591;
  max-width: 477px;
}

.summary {
  position: absolute;
  left: 125px;
  top: 520px;
  font-size: 17px;
  font-weight: 400;
  line-height: 1.6;
  opacity: 0.85;
  color: #1b1c1e;
  max-width: 477px;
}

.meta {
  position: absolute;
  left: 125px;
  top: 770px;
  font-size: 18px;
  font-weight: 400;
  line-height: 2.0;
  color: #1b1c1e;
}

.meta-label {
  font-weight: 600;
  color: #6d7278;
  font-size: 12px;
  letter-spacing: 1px;
  text-transform: uppercase;
  margin-bottom: 4px;
}

.footer {
  position: absolute;
  left: 125px;
  bottom: 56px;
  font-size: 16px;
  font-weight: 400;
  letter-spacing: 3px;
  opacity: 0.6;
  color: #1b1c1e;
  text-transform: uppercase;
}

/* Accent element: small teal bar */
.accent-bar {
  position: absolute;
  left: 125px;
  top: 220px;
  width: 50px;
  height: 4px;
  background: #217591;
}
</style>
</head>
<body>
<div class="cover-container">
  <!-- Layer 1: Background -->
  <div class="bg-layer">
    <div class="grid-pattern"></div>
  </div>

  <!-- Layer 2: Structure -->
  <div class="struct-layer">
    <div class="anchor-line"></div>
    <div class="meta-separator"></div>
  </div>

  <!-- Layer 3: Content -->
  <div class="content-layer">
    <div class="kicker">Rapport d'Audit Technique</div>
    <div class="accent-bar"></div>
    <div class="hero-title">HealthFlow<br>Guinea</div>
    <div class="summary">
      Analyse approfondie de l'architecture, de la securite et des performances du systeme d'information hospitalier.
      Recommandations priorisees et feuille de route pour la mise en production.
    </div>
    <div class="meta">
      <div class="meta-label">Organisation</div>
      <div>DataSphere Innovation</div>
      <div style="margin-top:16px;">
        <div class="meta-label">Directeur</div>
        <div>Sekouna KABA</div>
      </div>
      <div style="margin-top:16px;">
        <div class="meta-label">Date</div>
        <div>Mai 2026</div>
      </div>
    </div>
    <div class="footer">Analyse &amp; Recommandations v1.0</div>
  </div>
</div>
</body>
</html>"""

with open(cover_html_path, 'w', encoding='utf-8') as f:
    f.write(cover_html)

print(f"Cover HTML written: {cover_html_path}")

# Validate and render cover
import subprocess

PDF_SKILL_DIR = os.path.expanduser('~/my-project/skills/pdf')

# Run poster_validate.py check-html
validate_result = subprocess.run(
    ['python3', os.path.join(PDF_SKILL_DIR, 'scripts/poster_validate.py'), 'check-html', cover_html_path],
    capture_output=True, text=True
)
print(f"Cover validation: {validate_result.stdout}")
if validate_result.returncode != 0:
    print(f"Cover validation warnings: {validate_result.stderr}")

# Render cover via html2poster.js
render_result = subprocess.run(
    ['node', os.path.join(PDF_SKILL_DIR, 'scripts/html2poster.js'),
     cover_html_path, '--output', cover_pdf_path, '--width', '794px'],
    capture_output=True, text=True
)
print(f"Cover render: {render_result.stdout}")
if render_result.returncode != 0:
    print(f"Cover render errors: {render_result.stderr}")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MERGE COVER + BODY
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
from pypdf import PdfReader, PdfWriter, Transformation

A4_W, A4_H = 595.28, 841.89

def normalize_page_to_a4(page):
    box = page.mediabox
    w, h = float(box.width), float(box.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        sx, sy = A4_W / w, A4_H / h
        page.add_transformation(Transformation().scale(sx=sx, sy=sy))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page

writer = PdfWriter()

# Cover as page 1
if os.path.exists(cover_pdf_path):
    cover_page = PdfReader(cover_pdf_path).pages[0]
    writer.add_page(normalize_page_to_a4(cover_page))
    print("Cover page added")
else:
    print(f"WARNING: Cover PDF not found at {cover_pdf_path}")

# Body pages follow
if os.path.exists(body_path):
    for page in PdfReader(body_path).pages:
        writer.add_page(normalize_page_to_a4(page))
    print("Body pages added")
else:
    print(f"ERROR: Body PDF not found at {body_path}")

writer.add_metadata({
    '/Title': 'HealthFlow Guinea - Rapport d\'Audit, Recommandations et Evolutions',
    '/Author': 'DataSphere Innovation - Sekouna KABA',
    '/Creator': 'Z.ai',
    '/Subject': 'Audit technique du systeme d\'information hospitalier HealthFlow Guinea',
})

with open(output_path, 'wb') as f:
    writer.write(f)

print(f"\n{'='*60}")
print(f"FINAL PDF: {output_path}")
print(f"{'='*60}")

# Cleanup temp files
for temp in [cover_html_path, cover_pdf_path, body_path]:
    if os.path.exists(temp):
        os.remove(temp)
        print(f"Cleaned: {temp}")
